-- INSERT FORNECEDOR

INSERT INTO FORNECEDOR (FORN_NOME, FORN_TELEFONE, FORN_EMAIL, FORN_CNPJ, FORN_ENDERECO, FORN_STATUS) 
VALUES ('Tech Supplies Ltda', '(11) 98765-4321', 'contato@techsupplies.com.br', '12345678000195', 'Rua das Tecnologias, 123, São Paulo, SP', 'Ativo');

INSERT INTO FORNECEDOR (FORN_NOME, FORN_TELEFONE, FORN_EMAIL, FORN_CNPJ, FORN_ENDERECO, FORN_STATUS) 
VALUES ('Industrial Machines S.A.', '(21) 98765-4322', 'vendas@industrialmachines.com', '98765432000191', 'Avenida das Indústrias, 456, Rio de Janeiro, RJ', 'Ativo');

INSERT INTO FORNECEDOR (FORN_NOME, FORN_TELEFONE, FORN_EMAIL, FORN_CNPJ, FORN_ENDERECO, FORN_STATUS) 
VALUES ('Office Supplies EIRELI', '(31) 98765-4323', 'atendimento@officesupplies.com.br', '45678912000188', 'Praça dos Escritórios, 789, Belo Horizonte, MG', 'Ativo');

INSERT INTO FORNECEDOR (FORN_NOME, FORN_TELEFONE, FORN_EMAIL, FORN_CNPJ, FORN_ENDERECO, FORN_STATUS) 
VALUES ('Agro Equipamentos ME', '(41) 98765-4324', 'contato@agroequipamentos.com.br', '32165487000167', 'Estrada dos Campos, 1011, Curitiba, PR', 'Inativo');


-- INSERT PRODUTO
INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Notebook Dell XPS', 'Notebook de alto desempenho com processador Intel i7', 10, 1, 5000.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Impressora HP LaserJet', 'Impressora laser de alta velocidade', 5, 1, 1200.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Monitor Samsung 24"', 'Monitor Full HD de 24 polegadas', 15, 2, 800.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Teclado Mecânico Corsair', 'Teclado mecânico RGB para gamers', 20, 2, 350.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Mouse Logitech MX Master 3', 'Mouse sem fio ergonômico', 25, 2, 450.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Servidor Dell PowerEdge', 'Servidor de alta capacidade para empresas', 3, 1, 10000.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Cadeira Gamer DXRacer', 'Cadeira ergonômica para gamers', 10, 3, 1500.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('SSD Samsung 1TB', 'SSD de alta velocidade e capacidade', 30, 3, 600.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Memória RAM Kingston 16GB', 'Memória RAM DDR4 de alta performance', 50, 3, 400.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Placa de Vídeo NVIDIA RTX 3080', 'Placa de vídeo para alto desempenho gráfico', 5, 1, 7000.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Fonte Corsair 650W', 'Fonte de alimentação para PC', 15, 2, 500.00, 'Ativo');

INSERT INTO PRODUTO (PRODNOME, PRODDESCRICAO, PRODPONTOREP, FKIDFORN, PRODVALOR, PRODSTATUS) 
VALUES ('Headset HyperX Cloud II', 'Headset gamer com som surround', 20, 3, 300.00, 'Ativo');


-- INSERT USUARIO
INSERT INTO USUARIO (USU_PERMISSAO, USU_NOME, USU_CPF, EMAIL, USU_SENHA)
VALUES (1, 'Administrador', 'CPF 1', 'admin@admin.com', 'admin');

INSERT INTO USUARIO (USU_PERMISSAO, USU_NOME, USU_CPF, EMAIL, USU_SENHA)
VALUES (2, 'Funcionario', 'CPF 2', 'email2@example.com', 'senha2');

-- INSERT LOJA
INSERT INTO loja (loja_nome, loja_endereco, loja_contato)
VALUES ('Loja A', 'Rua Comercial, 123', '(11) 9876-5432');


INSERT INTO loja (loja_nome, loja_endereco, loja_contato)
VALUES ('Loja B', 'Av. Principal, 456', '(22) 1234-5678');

INSERT INTO loja (loja_nome, loja_endereco, loja_contato)
VALUES ('Loja C', 'Av. Principal, 226', '(22) 1234-5678');

-- Inserção de dados na tabela MOVIMENTACAOLOJA
INSERT INTO MOVIMENTACAOLOJA (FKIDLOJA, FKIDPROD, MOVQTDE, MOVVALOR, MOVPONTOREP) 
VALUES (1, 1, 10, 50.00, 100);

INSERT INTO MOVIMENTACAOLOJA (FKIDLOJA, FKIDPROD, MOVQTDE, MOVVALOR, MOVPONTOREP) 
VALUES (2, 1, 5, 30.00, 200);

-- Inserção de dados na tabela MOVIMENTACAOLOJA
INSERT INTO MOVIMENTACAOLOJA (FKIDLOJA, FKIDPROD, MOVQTDE, MOVVALOR, MOVPONTOREP) 
VALUES (1, 2, 10, 50.00, 100);

INSERT INTO MOVIMENTACAOLOJA (FKIDLOJA, FKIDPROD, MOVQTDE, MOVVALOR, MOVPONTOREP) 
VALUES (2, 2, 5, 30.00, 200);


-- Inserção 1 ESTOQUE
INSERT INTO ESTOQUE (ESTOQUEIDPROD,ESTOQUETRANSFERENCIA, ESTOQUETIPO, ESTOQUEQTD, ESTOQUEVALOR, ESTOQUEPONTOREP) 
VALUES (1, 0, 2, 100, 5000.00, 10);

INSERT INTO ESTOQUE (ESTOQUEIDPROD,ESTOQUETRANSFERENCIA, ESTOQUETIPO, ESTOQUEQTD, ESTOQUEVALOR, ESTOQUEPONTOREP) 
VALUES (2, 0, 1, 50, 1200.00, 5);

