CREATE TABLE PRODUTO (
  ID_PROD INT PRIMARY KEY AUTO_INCREMENT,
  PROD_NOME VARCHAR(255) NOT NULL,
  PROD_DESCRICAO VARCHAR(255) NOT NULL,
  PROD_PONTO_REP INT NOT NULL,
  ID_FORN INT,
  VALOR_QUANT DOUBLE,
  CONSTRAINT FK_PRODUTO_FORNECEDOR FOREIGN KEY (ID_FORN) REFERENCES FORNECEDOR(ID_FORN)
);