-- Tabela USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USU_PERMISSAO INT,
    USU_NOME VARCHAR(100),
    USU_CPF VARCHAR(14),
    EMAIL VARCHAR(100),
    USU_SENHA VARCHAR(100)
);

-- Tabela FORNECEDOR
CREATE TABLE FORNECEDOR (
  ID_FORN INT PRIMARY KEY AUTO_INCREMENT,
  FORN_NOME VARCHAR(50) NOT NULL,
  FORN_TELEFONE VARCHAR(20),
  FORN_EMAIL VARCHAR(50),
  FORN_CNPJ VARCHAR(14) NOT NULL,
  FORN_ENDERECO VARCHAR(255),
  FORN_STATUS VARCHAR(255)
);

-- Tabela PRODUTO
CREATE TABLE PRODUTO (
  PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
  PRODNOME VARCHAR(255) NOT NULL,
  PRODDESCRICAO VARCHAR(255) NOT NULL,
  PRODPONTOREP INT NOT NULL,
  FKIDFORN INT,
  PRODVALOR DOUBLE,
  PRODSTATUS VARCHAR(255) NOT NULL,
  CONSTRAINT FKIDFORN FOREIGN KEY (FKIDFORN) REFERENCES FORNECEDOR(ID_FORN)
);

CREATE TABLE LOJA (
  LOJA INT PRIMARY KEY AUTO_INCREMENT,
  LOJA_NOME VARCHAR(255) NOT NULL,
  LOJA_ENDERECO VARCHAR(255),
  LOJA_CONTATO VARCHAR(20)
);

CREATE TABLE MOVIMENTACAOLOJA (
    IDMOVIMENTACAO INT AUTO_INCREMENT PRIMARY KEY,
    FKIDLOJA INT NOT NULL,
    FKIDPROD INT NOT NULL,
    MOVQTDE INT NOT NULL,
    MOVVALOR DOUBLE NOT NULL,
    MOVPONTOREP INT NOT NULL,
    CONSTRAINT FKIDLOJA FOREIGN KEY (FKIDLOJA) REFERENCES LOJA(LOJA),
    CONSTRAINT FKIDPROD FOREIGN KEY (FKIDPROD) REFERENCES PRODUTO(PRODUTO)
);


CREATE TABLE ESTOQUE (
    ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
    ESTOQUETRANSFERENCIA INT NOT NULL,
    ESTOQUEIDPROD INT NOT NULL,
    ESTOQUETIPO INT NOT NULL,
    ESTOQUEQTD INT NOT NULL,
    ESTOQUEVALOR DOUBLE NOT NULL,
    ESTOQUEPONTOREP INT NOT NULL,
    CONSTRAINT ESTOQUEIDPROD FOREIGN KEY (ESTOQUEIDPROD) REFERENCES PRODUTO(PRODUTO)
);






